"""empty message

Revision ID: 00490a5b5d9b
Revises: ace46fc2b3ce
Create Date: 2020-06-05 20:33:12.836728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00490a5b5d9b'
down_revision = 'ace46fc2b3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
