"""empty message

Revision ID: 2b7041d2221f
Revises: 7bb12babf968
Create Date: 2020-06-03 19:31:38.587951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7041d2221f'
down_revision = '7bb12babf968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'categories')
    # ### end Alembic commands ###
