"""empty message

Revision ID: 34508ec90fd5
Revises: 00490a5b5d9b
Create Date: 2020-06-08 20:43:46.046465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34508ec90fd5'
down_revision = '00490a5b5d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_author_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_author_fkey', 'posts', 'users', ['author'], ['id'])
    # ### end Alembic commands ###
