"""empty message

Revision ID: 7dab2a62f67b
Revises: 6a93bd633b3a
Create Date: 2020-06-03 16:36:11.006097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dab2a62f67b'
down_revision = '6a93bd633b3a'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('foods',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('calories', sa.Integer(), nullable=True),
    # sa.Column('fat', sa.REAL(), nullable=True),
    # sa.Column('fiber', sa.REAL(), nullable=True),
    # sa.Column('protein', sa.REAL(), nullable=True),
    # sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    # sa.Column('image', sa.VARCHAR(length=400), nullable=True),
    # sa.Column('thumbnail', sa.VARCHAR(length=400), nullable=True),
    # sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    # sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    # sa.Column('author', sa.Integer(), nullable=False),
    # sa.Column('recipe', sa.TEXT(), nullable=True),
    # sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('foods')
    # ### end Alembic commands ###
