"""empty message

Revision ID: ace46fc2b3ce
Revises: 2b7041d2221f
Create Date: 2020-06-03 20:00:16.862683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace46fc2b3ce'
down_revision = '2b7041d2221f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=256), nullable=True))
    op.drop_column('posts', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
